global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'Auth-Service'
    scrape_interval: 5s
    static_configs:
      - targets: ['auth:3000']
  - job_name: 'Client-Service'
    scrape_interval: 5s
    static_configs:
      - targets: ['client:3001']
  - job_name: 'Product-Service'
    scrape_interval: 5s
    static_configs:
      - targets: ['product:3002']
  - job_name: 'Recommendations-Service'
    scrape_interval: 5s
    static_configs:
      - targets: ['recommendation:3003']
  - job_name: 'DB-User-Service'
    scrape_interval: 5s
    static_configs:
      - targets: ['db-user:5432']
  - job_name: 'DB-Client-Service'
    scrape_interval: 5s
    static_configs:
      - targets: ['db-client:5432']
  - job_name: 'DB-Product-Service'
    scrape_interval: 5s
    static_configs:
      - targets: ['db-product:5432']