apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      automountServiceAccountToken: false
      containers:
      - name: client
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "200m"
        image: jorgelvelasquez/client-service:latest
        ports:
        - containerPort: 3001
        env:
        - name: API_PREFIX
          valueFrom:
            configMapKeyRef:
              name: financial-config
              key: API_PREFIX_CLIENT
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: financial-config
              key: DB_HOST_CLIENT
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: financial-secret
              key: DB_USER_CLIENT
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: financial-secret
              key: DB_PASSWORD_CLIENT
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: financial-secret
              key: DB_NAME_CLIENT
        - name: DB_SYNCHRONIZE
          value: "true"
        - name: PORT
          value: "3001"
        - name: AUTH_HOST_API_VALID_TOKEN
          valueFrom:
            configMapKeyRef:
              name: financial-config
              key: AUTH_HOST_API_VALID_TOKEN
        command: ["/bin/sh", "-c"]
        args: ["until nc -zv db-client 5432; do sleep 5; done; exec node /usr/src/app/dist/main"]
