export enum Country {
  PERU = 'PE',
  ECUADOR = 'EC',
  COLOMBIA = 'CO',
  PANAMA = 'PA',
  USA = 'US',
  MEXICO = 'MX',
  BRASIL = 'BR',
  ARGENTINA = 'AR',
  CHILE = 'CL',
  URUGUAY = 'UY',
  PARAGUAY = 'PY',
  BOLIVIA = 'BO',
  VENEZUELA = 'VE',
}
