apiVersion: v1
kind: Secret
metadata:
    name: financial-secret
type: Opaque
data:
    DB_NAME_AUTH: dXNlci1kYg==
    DB_USER_AUTH: dXNlci1kYg==
    DB_PASSWORD_AUTH: dXMzci9kNHQ0L2I0czM=
    DB_NAME_CLIENT: Y2xpZW50LWRi
    DB_USER_CLIENT: Y2xpZW50LWRi
    DB_PASSWORD_CLIENT: Y2wxM250L2Q0dDQvYjRzMw==
    DB_NAME_PRODUCT: cHJvZHVjdC1kYg==
    DB_USER_PRODUCT: cHJvZHVjdC1kYg==
    DB_PASSWORD_PRODUCT: cHIwZHVjdC9kNHQ0L2I0czM=
    CLIENT_DB_NAME_RECOMMENDATION: Y2xpZW50LWRi
    CLIENT_DB_USER_RECOMMENDATION: Y2xpZW50LWRi
    CLIENT_DB_PASSWORD_RECOMMENDATION: Y2wxM250L2Q0dDQvYjRzMw==
    JWT_SECRET_AUTH: VXMzci1zM0NSM3Q=
