name: Run Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Run auth service tests
      run: |
        cd auth 
        npm run test

    - name: Run client service tests
      run: |
        cd client
        npm run test

    - name: Run product service tests
      run: |
        cd product  
        npm run test

    - name: Run recommendation service tests
      run: |
        cd recommendations
        npm run test